### ISSUE TITLE
monterey12.3.1无线蓝牙使用不了

### ISSUE THREAD

**Issue by chensingyou** [wtsjw/XiaoXin-Air15-IKBR-2018-EFI#4]
安装12.3.1，机型与说明一模一样。在安装过程中弹出助手提示“未能安装所需的固件更新”

**Comment by chensingyou** [comment]
找到解决办法：
修改config.plist
Kernel-Quirks-ThirdPartyDrivers ----- true
PlatformInfo-Automatic ----- true
Misc-Security-SecureBootModel ----- Disabled

**Comment by chensingyou** [comment]
Monterey12.3.1安装后，wifi和蓝牙都无法驱动。原ac3165无法驱动，更换dw1560也无法驱动。

**Comment by lunasaw** [comment]
博通网卡打勾可以驱动

**Comment by chensingyou** [comment]
更换了博通的网卡，相关驱动没有默认开启。将相关驱动都勾选后开机巨慢，开机后能识别出wifi硬件，但无法扫描和使用wifi，蓝牙仍然识别不了。有什么操作建议吗？十分感谢！🙏

**Comment by chensingyou** [comment]
找到问题了。将airportbrcmfixup.kext包内容中的AirPortBrcm4360_Injector.kext删掉即可正常使用wifi和蓝牙。lvs1974作者原文最底下“You have to block (or remove) AirPortBrcm4360_Injector.kext in 11+.”
